version: '3'

services:

  django_nginx_secure_link_db:
    container_name: pg10
    image: postgres:10
    env_file:
      - config/db/db_env
    networks:
      - db_network
    volumes:
      - db_volume:/var/lib/postgresql/data

  django_nginx_secure_link:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/opt/services/django_nginx_secure_link
      - static_volume:/opt/services/django_nginx_secure_link/static  # <-- bind the static volume
      - media_volume:/opt/services/django_nginx_secure_link/media  # <-- bind the media volume
      - ./backend/secure:/opt/services/django_nginx_secure_link/secure
    networks:
      - nginx_network
      - db_network
    depends_on:
      - django_nginx_secure_link_db

  nginx:
    container_name: nginx
    build: ./config/nginx
    ports:
      - 80:80
      - 443:443
      - 8000:8000
    volumes:
      - static_volume:/opt/services/django_nginx_secure_link/static  # <-- bind the static volume
      - media_volume:/opt/services/django_nginx_secure_link/media  # <-- bind the media volume
      - ./backend/secure:/opt/services/django_nginx_secure_link/secure
    networks:
      - nginx_network

  django_nginx_secure_frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/opt/services/django_nginx_secure_link/frontend
    networks:
      - nginx_network
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  db_volume:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume
